require("prototypes.betterbelts")
require("prototypes.betterweapons")
require("prototypes.betterenergy")
require("prototypes.betterrobots")
require("prototypes.nobotpickup")
require("prototypes.shotgunRecipieFix")
require("prototypes.moreintermediateproducts")